# Generated by Django 3.2.14 on 2023-01-02 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_user', localflavor.br.models.BRCPFField(help_text='Coluna com CPF do usuario', max_length=14, verbose_name='CPF_pk')),
                ('relation_with_uniso_user', models.CharField(choices=[('A', 'Aluno'), ('F', 'Funcionario'), ('T', 'Terceiro')], help_text='Coluna com a relacao do usuario com a UNISO', max_length=1, verbose_name='Relacao UNISO')),
                ('genero_user', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], help_text='Coluna com o genero do usuario', max_length=1, verbose_name='Genero')),
                ('ativo', models.BooleanField(null=True)),
                ('eh_motorista', models.BooleanField(null=True)),
                ('user', models.OneToOneField(help_text='Chave estrangeira conectando o user do django ao perfil do usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user_fk')),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(default='AAA-0000', help_text="Coluna com a placa do carro da carona, sendo padrao: 'XXX-0000'.", max_length=8, verbose_name='Placa')),
                ('user_id', models.OneToOneField(help_text='Coluna com o id do usuario que e motorista', on_delete=django.db.models.deletion.PROTECT, to='app.profile', verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotation', models.IntegerField(choices=[(1, 'Mais Um'), (2, 'Mais Dois'), (3, 'Mais Tres'), (4, 'Mais Quatro'), (5, 'Mais Cinco'), (6, 'Mais Seis')], default=3, help_text='Coluna com o numero da lotacao do carro da carona', verbose_name='Lotacao')),
                ('date_inicial_carona', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora iniciais da carona', verbose_name='Dat   a de inicio')),
                ('date_final_carona', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora finais da carona', verbose_name='Data final')),
                ('user_motorista', models.OneToOneField(help_text='Coluna com o motorista da carona', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
