# Generated by Django 3.2.14 on 2023-04-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230417_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='foto_carro',
            field=models.FileField(default='static/upload/foto_em_branco.png', upload_to='static/upload/motorista/'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='foto_motorista',
            field=models.FileField(default='static/upload/foto_em_branco.png', upload_to='static/upload/motorista/'),
        ),
    ]
