# Generated by Django 3.2.14 on 2023-04-20 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20230418_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carona',
            name='inicial_location',
            field=models.ForeignKey(help_text='Coluna com oa localizacao(latitude e longitude) inicial da carona', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='localizacao_inicial', to='app.localizacao', verbose_name='Localizacao inicial'),
        ),
        migrations.AlterField(
            model_name='carona',
            name='location_final',
            field=models.ForeignKey(help_text='Coluna com oa localizacao(latitude e longitude) final da carona', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.localizacao', verbose_name='Localizacao final'),
        ),
        migrations.AlterField(
            model_name='carona',
            name='user_motorista',
            field=models.ForeignKey(help_text='Coluna com o motorista da carona', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='foto_carro',
            field=models.FileField(default='static/upload/foto_em_branco.png', upload_to='static/upload/carro/'),
        ),
    ]
