# Generated by Django 3.2.14 on 2023-05-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230420_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='foto_cnh',
            field=models.FileField(default='static/upload/foto_em_branco.png', upload_to='static/upload/documento_cnh/'),
        ),
    ]
