# Generated by Django 3.2.14 on 2023-05-15 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_motorista_foto_cnh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carona',
            name='user_motorista',
            field=models.ForeignKey(help_text='Coluna com o motorista da carona', on_delete=django.db.models.deletion.PROTECT, to='app.motorista', verbose_name='Usuario'),
        ),
    ]
