# Generated by Django 3.2.14 on 2023-05-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_carona_user_motorista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carona',
            old_name='user_motorista',
            new_name='motorista',
        ),
        migrations.RenameField(
            model_name='motorista',
            old_name='user_id',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ativo',
        ),
    ]
