# Generated by Django 3.2.14 on 2023-05-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230515_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='foto_carro',
            field=models.FileField(default='upload/foto_em_branco.png', upload_to='static/upload/carro/'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='foto_cnh',
            field=models.FileField(default='upload/foto_em_branco.png', upload_to='static/upload/documento_cnh/'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='foto_motorista',
            field=models.FileField(default='upload/foto_em_branco.png', upload_to='static/upload/motorista/'),
        ),
    ]
