# Generated by Django 3.2.14 on 2023-05-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_profile_cpf_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='foto_carro',
            field=models.FileField(default='uploads/foto_em_branco.png', upload_to='uploads/carro/'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='foto_cnh',
            field=models.FileField(default='uploads/foto_em_branco.png', upload_to='uploads/documento_cnh/'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='foto_motorista',
            field=models.FileField(default='uploads/foto_em_branco.png', upload_to='uploads/motorista/'),
        ),
    ]
