# Generated by Django 3.2.14 on 2023-05-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20230518_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='eh_motorista',
            field=models.BooleanField(null=True, verbose_name='Quer ser motorista?'),
        ),
    ]
