# Generated by Django 3.2.14 on 2023-05-22 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20230522_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='profile',
            field=models.OneToOneField(help_text='Coluna com o id do usuario que e motorista', on_delete=django.db.models.deletion.PROTECT, related_name='motorista', to='app.profile', verbose_name='ID'),
        ),
    ]
