# Generated by Django 3.2.14 on 2023-05-22 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_alter_motorista_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='foto_carro',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/foto_carro/'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='foto_cnh',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/foto_documento_cnh/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(help_text='Chave estrangeira conectando o usuário do django ao perfil do usuário.', on_delete=django.db.models.deletion.PROTECT, related_name='use_r', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
