# Generated by Django 3.2.14 on 2023-05-23 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carona',
            name='date_inicial_carona',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora iniciais da carona.', verbose_name='Data de início'),
        ),
    ]
