# Generated by Django 3.2.14 on 2023-05-23 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_carona_date_inicial_carona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carona',
            name='motorista',
            field=models.ForeignKey(help_text='Coluna com o motorista da carona.', on_delete=django.db.models.deletion.PROTECT, related_name='carona', to='app.motorista', verbose_name='Usuario'),
        ),
    ]
