# Generated by Django 3.2.14 on 2023-05-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_carona_motorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacao',
            name='latitude',
            field=models.DecimalField(decimal_places=7, help_text='Representa a parte da coordenada: Latitude.', max_digits=11, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='longitude',
            field=models.DecimalField(decimal_places=7, help_text='Representa a parte da coordenada: Longitude.', max_digits=11, verbose_name='Longitude'),
        ),
    ]
