# Generated by Django 3.2.14 on 2023-05-24 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20230523_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='foto_carro',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/foto_carro/', verbose_name='Foto do carro da carona:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='foto_cnh',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/foto_documento_cnh/', verbose_name='Foto da sua CNH:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='foto_motorista',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/foto_motorista/', verbose_name='Sua foto:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='placa',
            field=models.CharField(default='AAA-0000', help_text="Coluna com a placa do carro da carona, seguindo o padrão: 'XXX-0000'.", max_length=8, verbose_name='Placa do carro'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='profile',
            field=models.OneToOneField(help_text='Coluna com o id do usuário, que é o motorista.', on_delete=django.db.models.deletion.PROTECT, related_name='motorista', to='app.profile', verbose_name='ID'),
        ),
    ]
