# Generated by Django 3.2.14 on 2023-05-25 14:32

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20230524_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='foto_carro',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.path_imagem_carro, verbose_name='Foto do carro da carona:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='foto_cnh',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.path_imagem_cnh, verbose_name='Foto da sua CNH:'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='foto_motorista',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.path_imagem_motorista, verbose_name='Sua foto:'),
        ),
    ]
